name: 05 - 1 - Event Filters and Activity
on:
  pull_request:
    types: [opened, synchronize]
    branches: main
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo test
        run: echo "Running whenever a PR is opened or synchronized AND base branch is main"
