name: 09 - Using Functions.
on:
  workflow_dispatch:

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR title
        run: echo "${{github.event.pull_request.title}}"
      - name: Print PR labels
        run: |
          cat << EOF
          ${{toJSON(github.event.pull_request.labels)}}
          EOF
      - name: Bug step
        if: ${{!cancelled() && contains(github.event.pull_request.title, 'fix')}}
        run: echo "I am a bug fix"
      - name: I will execute
        if: ${{ success() }}
        run: echo "I will print if previous steps succeed"
      - name: I will be skipped
        if: ${{ failure() }}
        run: echo "I will print if any previous step fails"
      - name: I will exeute"
        if: ${{ !cancelled() }}
        run: echo "I will execute"
      - name: I will exeute when cancelled
        if: ${{ cancelled() }}
        run: echo "I will print if the workflow has been cancelled."
