name: 09 - Using Functions.
on:
  pull_request:
  workflow_dispatch:

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 20 seconds
        run: sleep 20
      - name: Failing step
        run: exit 1
      - name: I will be skipped
        if: ${{ success() }}
        run: echo "I will print if previous steps succeed"
      - name: I will execute
        if: ${{ failure() }}
        run: echo "I will print if any previous step fails"
      - name: I will exeute when cancelled
        if: ${{ !cancelled() }}
        run: echo "I will execute"
      - name: I will exeute when cancelled
        if: ${{ cancelled() }}
        run: echo "I will print if the workflow has been cancelled."
